apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec: # define how the deployment should work
  replicas: 1 # number of pods to run
  selector: # select which pods to manage with this deployment
    matchLabels:
      app: simple-bank-api # all pods with this label will be managed by this deployemnt
  template: # define the pods that will be deployed
    metadata: # define the metadata of the pods
      labels:   # define the labels of the pods
        app: simple-bank-api # all pods with this label will be managed by this deployemnt
    spec: # define the pods specifications
      containers: # define the containers within the pod
      - name: simple-bank-api
        image: 927683992336.dkr.ecr.us-east-2.amazonaws.com/simple-bank:51fc6dfb21f55f9688a4490024fd91285c0adbd7
        ports:
        - containerPort: 8080